name: Deploy with Vertex AI Authentication

on:
  workflow_dispatch:  # Manual execution only
  # schedule:
  #   - cron: '*/30 * * * *'  # DISABLED - was sending videos every 30 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increased for video generation
    
    env:
      # Vertex AI credentials (original approach)
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Verify Vertex AI configuration
      run: |
        echo "🔑 Vertex AI credentials configured for Veo 3"
        echo "Project: ${GOOGLE_CLOUD_PROJECT}"
        echo "Creds: ${GOOGLE_APPLICATION_CREDENTIALS:0:20}..."
        
    - name: Test Vertex AI authentication
      run: |
        python test_veo3_simple.py
        
    - name: Run main application
      env:
        TELEGRAM_GENERAL_TOKEN: ${{ secrets.TELEGRAM_GENERAL_TOKEN }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        EMAIL_CONTACT: ${{ secrets.EMAIL_CONTACT }}
      run: |
        python multi_platform_engine.py