name: Deploy with Vertex AI Authentication

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increased for video generation
    
    env:
      # Gemini API Key for Veo 3 (NOT Vertex AI)
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Verify Gemini API configuration
      run: |
        echo "🔑 Gemini API Key configured for Veo 3"
        echo "API Key: ${GEMINI_API_KEY:0:10}...${GEMINI_API_KEY: -4}"
        
    - name: Test Vertex AI authentication
      run: |
        python test_veo3_simple.py
        
    - name: Run main application
      env:
        TELEGRAM_GENERAL_TOKEN: ${{ secrets.TELEGRAM_GENERAL_TOKEN }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        EMAIL_CONTACT: ${{ secrets.EMAIL_CONTACT }}
      run: |
        python multi_platform_engine.py